package Controller;


import java.awt.print.PrinterException;
import Model.dog;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.Color;

/**
 *
 * @author User
 */
public class doguk extends javax.swing.JFrame {

    /**
     * Creates new form doguk
     */
    public doguk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        kind = new javax.swing.JTextField();
        kind.setText("0");
        house = new javax.swing.JTextField();
        house.setText("0");
        food = new javax.swing.JTextField();
        food.setText("0");
        buttn = new javax.swing.JButton();
        cbb1 = new javax.swing.JComboBox<>();
        cbb2 = new javax.swing.JComboBox<>();
        cbb3 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        sp1 = new javax.swing.JSpinner();
        sp2 = new javax.swing.JSpinner();
        sp3 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        OutPut2 = new javax.swing.JTextArea();
        ButtnPrint = new javax.swing.JButton();
        ButtonExit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ButtonPay = new javax.swing.JButton();
        pay = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 155, 124));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("寵物店");
        
        btnNewButton = new JButton("前往領養系統");
        btnNewButton.setBackground(new Color(255, 105, 180));
        btnNewButton.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		dispose();
        		new adoption().setVisible(true);
        	}
        });
        btnNewButton.setFont(new Font("新細明體", Font.PLAIN, 20));
        
        btnNewButton_1 = new JButton("返回登入系統");
        btnNewButton_1.setBackground(new Color(255, 105, 180));
        btnNewButton_1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		dispose();
        		new login().setVisible(true);
        	}
        });
        btnNewButton_1.setFont(new Font("新細明體", Font.PLAIN, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(btnNewButton_1, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
        					.addGap(128)
        					.addComponent(jLabel1))
        				.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(321, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel1)
        				.addComponent(btnNewButton_1, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        jPanel2.setBackground(new java.awt.Color(223, 193, 159));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("姓名");

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("狗狗");

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("狗屋");

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("飼料");

        name.setBackground(new java.awt.Color(249, 242, 242));

        kind.setBackground(new java.awt.Color(249, 242, 242));
        kind.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 17)); // NOI18N
        kind.setForeground(new java.awt.Color(51, 51, 51));

        house.setBackground(new java.awt.Color(249, 242, 242));
        house.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 17)); // NOI18N
        house.setForeground(new java.awt.Color(51, 51, 51));

        food.setBackground(new java.awt.Color(249, 242, 242));
        food.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 17)); // NOI18N
        food.setForeground(new java.awt.Color(51, 51, 51));

        buttn.setBackground(new java.awt.Color(245, 99, 73));
        buttn.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 30)); // NOI18N
        buttn.setForeground(new java.awt.Color(51, 51, 51));
        buttn.setText("確定購買");
        buttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttnMouseClicked(evt);
            }
        });

        cbb1.setBackground(new java.awt.Color(249, 242, 242));
        cbb1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 17)); // NOI18N
        cbb1.setForeground(new java.awt.Color(51, 51, 51));
        cbb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "請選擇", "二哈", "柴犬", "貴賓", "博美" }));
        cbb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb1ActionPerformed(evt);
            }
        });

        cbb2.setBackground(new java.awt.Color(249, 242, 242));
        cbb2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 17)); // NOI18N
        cbb2.setForeground(new java.awt.Color(51, 51, 51));
        cbb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "請選擇", "別墅", "狗窩", "公園" }));
        cbb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb2ActionPerformed(evt);
            }
        });

        cbb3.setBackground(new java.awt.Color(249, 242, 242));
        cbb3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 17)); // NOI18N
        cbb3.setForeground(new java.awt.Color(51, 51, 51));
        cbb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "請選擇", "好好吃飼料", "好難吃飼料" }));
        cbb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("選項");

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("單價");

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        rb1.setForeground(new java.awt.Color(51, 51, 51));
        rb1.setText("普通會員(9折)");
        rb1.setToolTipText("");
        rb1.setActionCommand("普通會員(9折)");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        rb2.setForeground(new java.awt.Color(51, 51, 51));
        rb2.setText("白金VIP (8折)");

        buttonGroup1.add(rb3);
        rb3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        rb3.setForeground(new java.awt.Color(51, 51, 51));
        rb3.setText("黃金VIP (7折)");
        rb3.setToolTipText("");

        sp1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 17)); // NOI18N
        sp1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 17)); // NOI18N
        sp2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 17)); // NOI18N
        sp3.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("數量");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbb1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbb2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbb3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sp2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(sp3)
                                    .addComponent(sp1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(house, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kind, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(food, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(rb1)
                        .addGap(33, 33, 33)
                        .addComponent(rb2)
                        .addGap(57, 57, 57)
                        .addComponent(rb3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(buttn, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(kind, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sp1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(house, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(food, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb1)
                    .addComponent(rb2)
                    .addComponent(rb3))
                .addGap(97, 97, 97)
                .addComponent(buttn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        jPanel3.setBackground(new java.awt.Color(245, 208, 172));

        output.setBackground(new java.awt.Color(249, 242, 242));
        output.setColumns(20);
        output.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        output.setForeground(new java.awt.Color(51, 51, 51));
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("   明細");

        OutPut2.setBackground(new java.awt.Color(249, 242, 242));
        OutPut2.setColumns(20);
        OutPut2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        OutPut2.setForeground(new java.awt.Color(51, 51, 51));
        OutPut2.setRows(5);
        jScrollPane2.setViewportView(OutPut2);

        ButtnPrint.setBackground(new java.awt.Color(249, 242, 242));
        ButtnPrint.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 25)); // NOI18N
        ButtnPrint.setForeground(new java.awt.Color(51, 51, 51));
        ButtnPrint.setText("列印明細");
        ButtnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtnPrintMouseClicked(evt);
            }
        });

        ButtonExit.setBackground(new java.awt.Color(249, 242, 242));
        ButtonExit.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 25)); // NOI18N
        ButtonExit.setForeground(new java.awt.Color(51, 51, 51));
        ButtonExit.setText("離開");
        ButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonExitMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("付款");

        ButtonPay.setBackground(new java.awt.Color(249, 242, 242));
        ButtonPay.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        ButtonPay.setForeground(new java.awt.Color(51, 51, 51));
        ButtonPay.setText("結帳");
        ButtonPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonPayMouseClicked(evt);
            }
        });

        pay.setBackground(new java.awt.Color(249, 242, 242));
        pay.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        pay.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(ButtnPrint)
                                .addGap(87, 87, 87)
                                .addComponent(ButtonExit)))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(ButtonPay, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ButtonPay, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnMouseClicked
       
        String Name = name.getText();        
        int dogAmount =(int)sp1.getValue();
        int houseAmount = (int)sp2.getValue();
        int foodAmount = (int)sp3.getValue();
        int dogPrice = Integer.parseInt(kind.getText());
        int housePrice = Integer.parseInt( house.getText());
        int foodPrice = Integer.parseInt( food.getText());

        dog d = new dog(Name,dogPrice*dogAmount,housePrice*houseAmount,foodPrice*foodAmount);
                              
        if(rb1.isSelected()){ 
            output.setText(d.showpublic()+"\n普通會員 總價= "+(int)(d.getSum()*0.9));
            
        }
        else if(rb2.isSelected()){
            output.setText(d.showpublic()+"\n白金會員 總價= "+(int)(d.getSum()*0.8));
        }
        else if(rb3.isSelected()){
           output.setText(d.showpublic()+"\n黃金會員 總價= "+(int)(d.getSum()*0.7));
        }
        else{
        	output.setText(d.showpublic()+"\n無會員身分 總價= "+(int)(d.getSum()));
        }
    }//GEN-LAST:event_buttnMouseClicked

    private void cbb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb1ActionPerformed
        // TODO add your handling code here:
        String a= cbb1.getSelectedItem().toString();
        
        if(a == "請選擇"){
     
            kind.setText("0");
        }
        
        else if(a == "二哈"){
            
            kind.setText("5000");
        }
        else if(a == "柴犬"){
            
            kind.setText("4000");
        }
        else{
            
            kind.setText("3000");
        }
    }//GEN-LAST:event_cbb1ActionPerformed

    private void cbb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb2ActionPerformed
        // TODO add your handling code here:
        String a= cbb2.getSelectedItem().toString();
        
        if(a == "請選擇"){
            
            house.setText("0");
        }
        
        else if(a == "別墅"){
           
            house.setText("50000");
        }
        else if(a == "狗窩"){
           
            house.setText("5000");
        }
        else{
           
            house.setText("0");
        }
    }//GEN-LAST:event_cbb2ActionPerformed

    private void cbb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb3ActionPerformed
        // TODO add your handling code here:
        String a= cbb3.getSelectedItem().toString();
        
        if(a == "請選擇"){
           
            food.setText("0");
        }
        else if(a=="好好吃飼料"){
          
            food.setText("4000");
        }
        else{
         
            food.setText("1000");
        }
    }//GEN-LAST:event_cbb3ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void ButtnPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtnPrintMouseClicked
        // TODO add your handling code here:            
        try{  
            OutPut2.print();
        }    
        catch(PrinterException e){    
            
        }
    }//GEN-LAST:event_ButtnPrintMouseClicked

    private void ButtonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_ButtonExitMouseClicked
    
    private void ButtonPayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPayMouseClicked
        // TODO add your handling code here:
        String Name = name.getText();
        String Kind = kind.getText();
        String House = house.getText();
        String Food = food.getText();
        int A =(int)sp1.getValue();
        int B = (int)sp2.getValue();
        int C = (int)sp3.getValue();
        int K = Integer.parseInt(Kind);
        int H = Integer.parseInt(House);
        int F = Integer.parseInt(Food);

        dog d = new dog(Name,K*A,H*B,F*C);
          
        String Pay = pay.getText();
        int P = Integer.parseInt(Pay);  
        
        if(rb1.isSelected()){
             OutPut2.setText(d.show2(P,(int)(d.getSum()*0.9)));
      
        }
        else if(rb2.isSelected()){
            OutPut2.setText(d.show2(P,(int)(d.getSum()*0.8)));
        }
        else if(rb3.isSelected()){
            OutPut2.setText(d.show2(P,(int)(d.getSum()*0.7)));
        }
        
        
    }//GEN-LAST:event_ButtonPayMouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doguk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doguk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doguk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doguk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doguk().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtnPrint;
    private javax.swing.JButton ButtonExit;
    private javax.swing.JButton ButtonPay;
    private javax.swing.JTextArea OutPut2;
    private javax.swing.JButton buttn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbb1;
    private javax.swing.JComboBox<String> cbb2;
    private javax.swing.JComboBox<String> cbb3;
    private javax.swing.JTextField food;
    private javax.swing.JTextField house;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kind;
    private javax.swing.JTextField name;
    private javax.swing.JTextArea output;
    private javax.swing.JTextField pay;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JSpinner sp1;
    private javax.swing.JSpinner sp2;
    private javax.swing.JSpinner sp3;
    private JButton btnNewButton;
    private JButton btnNewButton_1;
    // End of variables declaration//GEN-END:variables
}
